# toutes les LXC à setup
# si c'est déjà fait ansible va skip
all:
  vars:
    ansible_user: admin
  hosts:
    actions-runner: 
      ansible_host: 192.168.10.11
    wireguard:
      ansible_host: 192.168.10.12
    caddy:
      ansible_host: 192.168.10.13
    cloudflared:
      ansible_host: 172.16.10.12
    kanboard:
      ansible_host: 192.168.10.14
