# poc typique pour un déploiement automatisé Komodo
# (Checkov détecte les environnements et secrets comme problème vu que c'est hardcodé, sauf que c'est un poc donc ca ne fait pas sens)
# désactivé ici, donc environment à mettre (voir https://docs.kanboard.org/v1/admin/docker/)
name: kanboard

services:
  app:
    image: ${KANBOARD_IMAGE:-kanboard/kanboard:latest}
    container_name: kanboard
    restart: always
    volumes:
      - data:/var/www/app/data
      - plugins:/var/www/app/plugins
      - certs:/etc/nginx/ssl 
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanboard.rule=Host(`kanboard-poc.host.blavogiez.fr`)"
      - "traefik.http.routers.kanboard.entrypoints=web"
      - "traefik.http.services.kanboard.loadbalancer.server.port=80"
    networks:
      - default
      - proxy

  db:
    image: postgres:15-alpine
    restart: always 
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kanboard"]
      start_period: 15s
      interval: 10s
      timeout: 5s
    networks:
      - default

volumes:
  data:
  plugins:
  certs:
  db:

networks:
  default:
  proxy:
    external: true
